name: python

on:
  schedule:
    - cron: '0 6 * * *'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python lnrelease/lnrelease.py

      - name: Commit and push
        run: |
          git add -A
          if git diff --staged --quiet; then
            echo "Finished, no changes"
          else
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git commit -m "update"
            git push
          fi
