name: python

on:
  schedule:
    - cron: '0 6 * * *'

  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      deploy: ${{ steps.commit.outputs.deploy }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script
        run: python lnrelease/lnrelease.py

      - name: Commit and push
        id: commit
        run: |
          git add -u
          if git diff --staged --quiet; then
            echo "Finished, no changes"
            echo "deploy=false" >> $GITHUB_OUTPUT
          else
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            git commit -m "update"
            git push
            echo "deploy=true" >> $GITHUB_OUTPUT
          fi

  deploy:
    needs: update
    if: needs.update.outputs.deploy == 'true'
    uses: ./.github/workflows/pages.yml
